name: Margovia
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0069fd'
    - '#dbe6fa'
    - '#080b00'
    - '#937e00'
    - '#5aadfc'
  brandStrength: 0.9142126112710685
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
